version: "3.8"
services:
    api:
        build: .
        container_name: api
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - redis

    celery:
        build: .
        command: celery -A core worker -l INFO
        volumes:
            - .:/usr/src/app
        depends_on:
            - api
            - redis

    redis:
        image: "redis:alpine"
