# Generated by Django 4.1 on 2022-09-16 18:32

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_deleted", models.BooleanField(default=False, verbose_name="is deleted")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=14,
                        null=True,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="subject")),
                ("message", models.TextField(verbose_name="message")),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
    ]
