# Generated by Django 4.1 on 2022-08-17 19:40

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='slug')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='image')),
                ('source_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='source code')),
                ('demo_link', models.CharField(blank=True, max_length=128, null=True, verbose_name='demo link')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
