# Generated by Django 4.1 on 2022-09-14 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="name")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
        migrations.AlterField(
            model_name="project",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="body"),
        ),
    ]
