# Generated by Django 4.1 on 2022-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="project.tag"),
        ),
    ]
