# Generated by Django 4.1 on 2022-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_project_image_alter_project_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="projects", to="project.tag"),
        ),
    ]
