# Generated by Django 4.1 on 2022-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_project_image_alter_project_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="featured"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="projects", to="project.tag"),
        ),
    ]
