# Generated by Django 4.1 on 2022-10-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_project_tags"),
        ("project", "0006_project_featured_alter_project_tags"),
    ]

    operations = []
