# Generated by Django 4.1 on 2022-09-15 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("pkid", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_deleted", models.BooleanField(default=False, verbose_name="is deleted")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.CharField(max_length=255, verbose_name="description")),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
                "ordering": ("-created_at", "-updated_at"),
            },
        ),
    ]
