# Generated by Django 4.1 on 2022-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_alter_skill_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="proficiency",
            field=models.TextField(
                choices=[
                    ("beginner", "beginner"),
                    ("moderate", "moderate"),
                    ("advance", "advance"),
                    ("pro", "pro"),
                ],
                default="beginner",
                verbose_name="profiency",
            ),
        ),
    ]
